FROM node:lts-alpine

WORKDIR /app

COPY package-lock.json ./
COPY package.json ./
COPY services/inventory/package.json ./services/inventory/package.json

RUN npm ci

COPY . ./

CMD [ "npm", "--workspace", "inventory", "run", "dev" ]
