FROM node:lts-alpine AS builder

WORKDIR /root

COPY package-lock.json ./
COPY package.json ./
COPY apps/web/package.json ./apps/web/

RUN npm ci

COPY . ./

RUN npm --workspace web run build

FROM nginx:alpine AS runtime

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /root/apps/web/build /usr/share/nginx/html
