FROM node:lts-alpine AS builder

WORKDIR /root

COPY package-lock.json ./
COPY package.json ./
COPY services/accounts/package.json ./services/accounts/package.json

RUN npm ci

COPY . ./

RUN npm --workspace accounts run build

FROM node:lts-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /root

COPY --from=builder /root/services/accounts/build/* ./

CMD [ "node", "--enable-source-maps", "start.cjs" ]
