FROM node:lts-alpine

WORKDIR /app

COPY package-lock.json ./
COPY package.json ./
COPY services/accounts/package.json ./services/accounts/package.json

RUN npm ci

COPY . ./

CMD [ "npm", "--workspace", "accounts", "run", "dev" ]
