services:
  web:
    container_name: "web"
    build:
      context: "."
      dockerfile: "apps/web/dockerfile"
    ports:
      - "3000:80"

  gateway:
    container_name: "gateway"
    build:
      context: "."
      dockerfile: "services/gateway/dockerfile"
    environment:
      ACCOUNTS_ENDPOINT: "http://accounts:4001/graphql"
      INVENTORY_ENDPOINT: "http://inventory:4002/graphql"
      PRODUCTS_ENDPOINT: "http://products:4003/graphql"
      REVIEWS_ENDPOINT: "http://reviews:4004/graphql"
    ports:
      - "4000:4000"

  accounts:
    container_name: "accounts"
    build:
      context: "."
      dockerfile: "services/accounts/dockerfile"
    ports:
      - "4001:4001"

  inventory:
    container_name: "inventory"
    build:
      context: "."
      dockerfile: "services/inventory/dockerfile"
    ports:
      - "4002:4002"

  products:
    container_name: "products"
    build:
      context: "."
      dockerfile: "services/products/dockerfile"
    ports:
      - "4003:4003"

  reviews:
    container_name: "reviews"
    build:
      context: "."
      dockerfile: "services/reviews/dockerfile"
    ports:
      - "4004:4004"
