FROM node:lts-alpine

WORKDIR /app

COPY package-lock.json ./
COPY package.json ./
COPY services/gateway/package.json ./services/gateway/package.json

RUN npm ci

COPY . ./

CMD [ "npm", "--workspace", "gateway", "run", "dev" ]
