FROM node:lts-alpine

WORKDIR /app

COPY package-lock.json ./
COPY package.json ./
COPY services/reviews/package.json ./services/reviews/package.json

RUN npm ci

COPY . ./

CMD [ "npm", "--workspace", "reviews", "run", "dev" ]
