FROM node:lts-alpine AS builder

WORKDIR /root

COPY package-lock.json ./
COPY package.json ./
COPY services/reviews/package.json ./services/reviews/package.json

RUN npm ci

COPY . ./

RUN npm --workspace reviews run build

FROM node:lts-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /root

COPY --from=builder /root/services/reviews/build/* ./

CMD [ "node", "--enable-source-maps", "start.cjs" ]
