FROM node:lts-alpine AS builder

WORKDIR /root

COPY package-lock.json ./
COPY package.json ./
COPY apps/admin/package.json ./apps/admin/

RUN npm ci

COPY . ./

RUN npm --workspace admin run build

FROM nginx:alpine AS runtime

COPY apps/admin/nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /root/apps/admin/build /usr/share/nginx/html
