FROM node:lts-alpine

WORKDIR /app

COPY package-lock.json ./
COPY package.json ./
COPY services/products/package.json ./services/products/package.json

RUN npm ci

COPY . ./

CMD [ "npm", "--workspace", "products", "run", "dev" ]
