FROM node:lts-alpine AS builder

WORKDIR /root

COPY package-lock.json ./
COPY package.json ./
COPY services/products/package.json ./services/products/package.json

RUN npm ci

COPY . ./

RUN npm --workspace products run build

FROM node:lts-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /root

COPY --from=builder /root/services/products/build/* ./

CMD [ "node", "--enable-source-maps", "start.cjs" ]
